# Generated by Django 4.1.3 on 2022-12-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='tilte',
        ),
        migrations.AddField(
            model_name='blog',
            name='chead0',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blog',
            name='chead1',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blog',
            name='chead2',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
