# Generated by Django 4.1.3 on 2022-12-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_orders_amount_orders_amountt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amountt',
        ),
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
