# Generated by Django 4.1.3 on 2022-12-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_orders_address_alter_orders_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='amount',
            new_name='bill',
        ),
    ]
