# Generated by Django 4.1.3 on 2022-12-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_amount_orders_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='bill',
        ),
    ]
