# Generated by Django 4.1.3 on 2022-12-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_orders_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='amount',
            new_name='bill',
        ),
    ]
