# Generated by Django 4.1.3 on 2022-12-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_rename_amount_orders_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='bill',
            new_name='amount',
        ),
    ]
